### ISSUE TITLE
can't `get-app` with "bench.utils.CommandFailedError: git clone https://github.com/newmatik/dunning  --depth 1 --origin upstream"

### ISSUE THREAD

**Issue by dulhaver** [newmatik/dunning#33]
in order to check this out I try to install the app in a v12 instance (running in a linux container)

I can't `get-app` the app to begin with

```
~/frappe-bench$ bench get-app dunning https://github.com/newmatik/dunning
INFO:bench.app:getting app dunning
INFO:bench.utils:git clone https://github.com/newmatik/dunning  --depth 1 --origin upstream
Cloning into 'dunning'...
fatal: unable to access 'https://github.com/newmatik/dunning/': Could not resolve host: github.com
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/franch/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/franch/.bench/bench/commands/make.py", line 41, in get_app
    get_app(git_url, branch=branch)
  File "/home/franch/.bench/bench/app.py", line 125, in get_app
    cwd=os.path.join(bench_path, 'apps'))
  File "/home/franch/.bench/bench/utils.py", line 161, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: git clone https://github.com/newmatik/dunning  --depth 1 --origin upstream
```

**Comment by dulhaver** [comment]
tried another v12 test instance where installation works. So, I am closing this again as it seems to be a local issue.
